### ISSUE TITLE
Implement Recommended Content and UI Changes to Field Descriptions

### ISSUE THREAD

**Issue by jmbarne3** [UCF/unify-events#146]
Based on the recommendations provided by #144 and #145, the field description updates should be implemented along with any UI improvements that can be done within a 4 hour development period (including review time).

## Done
Field descriptions should be updated per the referenced documentation (see comment below) and, if time allows, any UI improvements recommended made.

**Comment by kimberspencer** [comment]
Here are two possible solutions: 

1. [We tweak some of the form field descriptions](https://docs.google.com/document/d/1T0c_pEQt-T8rmFv-yVlZgpXqnOJ3P1n1pxTrtEXLtU4/edit#heading=h.l4j7qzsxewqn) and add links to the related sections on the Help page. This allows people to get information on a specific field. This will be a quicker solution.

2. [We put the short descriptions in a modal](https://docs.google.com/document/d/1T0c_pEQt-T8rmFv-yVlZgpXqnOJ3P1n1pxTrtEXLtU4/edit#heading=h.pfkkwb3gt9du) (hover/click a question mark/light bulb) and put a link to the Help page for more info. This solution will take more time than just updating the descriptions. 

The solution we go with will depend on time it takes to implement and preferred UI/UX.

The Help doc will also need updated to include anchor links to each of the form field description we link to.
