### ISSUE TITLE
Create an Initial Promotion for Production

### ISSUE THREAD

**Issue by jmbarne3** [UCF/unify-events#150]
Create an initial promotion to use when the code is pushed to production. This will require an image, an alt to be used with the image and the URL to be used.

## Done
Provide developers with the image, alt and URL to be used for the initial promotion to be used in production.

**Comment by kimberspencer** [comment]
Created a Think30 promo using the Admin. Same as on myUCF. Can't preview it - would be a nice feature for a future sprint.
