### ISSUE TITLE
Create list of "Trusted" Calendars

### ISSUE THREAD

**Issue by jmbarne3** [UCF/unify-events#158]
Using the two spreadsheets generated last week (you can find them in Slack), generate a list of calendars that will be marked as "Trusted" after this sprint is completed and the code pushed to production.

## Done
The list should at a minimum include the IDs of the calendars that need to be set as "Trusted" but could also include the calendar title for convenience. It should be provided as a CSV file to the development team so we can pull the list of owners and admins to contact.

**Comment by kimberspencer** [comment]
Provided a list of trusted calendars via Slack on Sept 20.
