### ISSUE TITLE
RSS, XML, JSON, and ICS daily and weekly feeds are paginated

### ISSUE THREAD

**Issue by mark-ignacio** [UCF/unify-events#2]
All feeds (ics, rss, json, xml) are currently paginated to 25 objects. This is most obvious with particularly busy weeks, like the week this pull request was submitted. You can see the paginated feed here: 

https://events.ucf.edu/this-week/feed.rss
https://events.ucf.edu/this-week/feed.rss?page=2

I don't think limiting feed items was intended behavior, since a workaround to this is just getting the current month and filtering events by date range.

**Comment by jmbarne3** [comment]
As noted in the response to the pull request, the pagination on the feeds is intended. We will, however, attempt to add some page linking to the rss feeds. Any updates to the xml and json feeds will be tracked in a separate issue, most likely internally.

**Comment by mark-ignacio** [comment]
This answer is disappointing to me because I was hoping to use the iCalendar feed and the RFC doesn't support pagination.

I don't buy the negative client side behavior reason stated in your response to the pull request because it's currently possible to pull down thousands of events by pulling down the [unpaginated monthly view](https://github.com/UCF/unify-events/blob/b7aa928100467cdd2160680df9e26ab1ec3abe79/apps/events/views/event_views.py#L594) feed. The comment in the code I just linked suggests that pagination was disabled for a different reason. I'd suggest paginating that feed as well if you want to be consistent with client side performance.
