### ISSUE TITLE
User Permissions Reset

### ISSUE THREAD

**Issue by jmbarne3** [UCF/unify-events#4]
All users, other than the owner of a calendar, lose access to that calendar if the name of the calendar is changed. So, for example, if the calendar name is "Department Calendar" and it is changed to "Division Calendar", only the owner of "Department Calendar" would still have access to the newly renamed "Division Calendar". Original poster also noted that changing the name back to its original name, i.e. "Department Calendar", does not result in users regaining their access.

**Comment by schrauger** [comment]
I didn't realize this was on GitHub. I'll be sure to add any bug reports here now that I know about it. Thanks for looking into this!

**Comment by cjg89** [comment]
This bug is fixed on events.ucf.edu as of a few minutes ago.  Thanks again for reporting this!
