### ISSUE TITLE
Update tag autocomplete form to perform case-insensitive searches/matches

### ISSUE THREAD

**Issue by cjg89** [UCF/unify-events#9]
Currently, due to how we handle tag matches in the tag insertion/lookup field for the create/update event form, you can end up in situations such as in the screenshot below.  We need to ensure that similar tags with different casing do not add duplicate tags to the new tag list.

<img width="1246" alt="screen_shot_2018-03-12_at_10 54 55_am" src="https://user-images.githubusercontent.com/1649216/37292111-2f989f50-25de-11e8-8909-1354c9ed497f.png">

**Comment by jmbarne3** [comment]
This particular issue shouldn't be a problem anymore. There's an additional issue with tags being able to be duplicated within the UI by adding an existing tag (highlight the typeahead result, then click/enter) and then adding a new tag with the same value (just pressing enter after typing it in fully). However, testing confirms that the tag is being deduped when being added via taggit on the backend.
